"""The depot's inspection checklists, frozen as of migration 0014.

Read out of MBMT's own D.I and ten-day sheets by `scripts/seed_checklists.py`,
then captured here so a deployment no longer needs the spreadsheets. They are
not in the repository and never will be — `.gitignore` keeps a customer's
operational records out of the history — which meant a fresh database migrated
to head had the checklist tables and nothing to put in them.

**Do not edit this file.** A migration that has run somewhere is history, and
0014 reads these values. If the depot revises a sheet, add `checklists_v2.py`
and a migration that applies it; leave this one as the record of what v1 was.

D.I 14/12/14 by bus model, ten-day 57 each: 211 lines, about 15 kB.
"""
from __future__ import annotations

from typing import Any

#: One entry per (work_type_code, variant), each with its lines in sheet order.
CHECKLISTS: list[dict[str, Any]] = [
    {
        "work_type_code": "10 DAYS SERVICE",
        "variant": "12M AC",
        "name": "10 day inspection — 12M AC",
        "items": [
            {
                "section": "Inside Bus",
                "label": "Check LV battery voltage on display",
                "sort_order": 0,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for parking brake function and symbol on display",
                "sort_order": 1,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for any fault codes on display",
                "sort_order": 2,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for steering system functionality - vibration or hardness while rotating",
                "sort_order": 3,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for led signals on display while operating combination switch and functionality of switch",
                "sort_order": 4,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for all dashboard switches working and function - interior lights, ITS,hazard light, emergency declare, doors etc.",
                "sort_order": 5,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for ITS system functionality - bdc function, speakers, announcement, destinations change, mike and all camera functions",
                "sort_order": 6,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for air condition system functionality - cooling and all blowers function (Optional)",
                "sort_order": 7,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for all USB port - function, burn marks, damages and missing",
                "sort_order": 8,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for all passenger doors operation (proper opening & closing), warning & safety function",
                "sort_order": 9,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for wiper system functionality and condition",
                "sort_order": 10,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for stanchion poles vibrations, seats and interior for any abnormalities for rusting, damage, painting etc.",
                "sort_order": 11,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for proper routing of lv wiring harness near steering column, controllers, inside dashboard",
                "sort_order": 12,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for any fuse or relay failures in interior fuse box",
                "sort_order": 13,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for main fuses (big fuses) proper mounting at LV battery compartment",
                "sort_order": 14,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check lv battery condition - voltage(bus power off), leads conditions, terminals fastening",
                "sort_order": 15,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check for all exterior lights functionality - front, parking, tail lamps & indicators",
                "sort_order": 16,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check for electric horns function",
                "sort_order": 17,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check all tyres wear, damages and deformity",
                "sort_order": 18,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check all wheel nuts and torque markings",
                "sort_order": 19,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check orvms for proper positioning and any damages",
                "sort_order": 20,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check for all flap doors locking, proper open/close, gas springs condition",
                "sort_order": 21,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check for any glass and body damages",
                "sort_order": 22,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check all LV & HV controllers for proper mounting and connectors positive locking (Rear Compartment)",
                "sort_order": 23,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check rear fuse box for proper mounting, any fuse or relay failure and any loose cables form fuse box",
                "sort_order": 24,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check all lv wiring harness for proper routing and any damages inside rear compartment",
                "sort_order": 25,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check air compressor oil levels, any leakages and abnormal noise.",
                "sort_order": 26,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check for any air leakages from air compressor lines, connectors and air dryer assembly",
                "sort_order": 27,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check steering motor and oil filter assembly for oil level, leakages and any abnormal noise",
                "sort_order": 28,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check steering motor and air compressor assembly mounting pads",
                "sort_order": 29,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check for motor coolant line assembly for coolant levels, any leakages, proper connectivity and rubber hose damages",
                "sort_order": 30,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check for coolant circulation - pumps working & clean radiator with compressed air",
                "sort_order": 31,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "HV Battery",
                "label": "Check for HV battery coolant level and coolant line condition for any leakages, rubber hose condition and routing.",
                "sort_order": 32,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "HV Battery",
                "label": "Check for HV battery coolant system working",
                "sort_order": 33,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check for HV battery mountings nuts & bolt & retighting with torque (",
                "sort_order": 34,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check all air lines and valves (EBS, brake modulators, suspension, ECAS solenoid valve etc.) for any air leakage",
                "sort_order": 35,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check all shock absorbers for any oil leakage and air springs condition and any air leakages. Retight with Shockabsorber bolts with torque",
                "sort_order": 36,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check all bushes for any damage or deformities - Anti Roll Bar, Link Rod, Traction Rods",
                "sort_order": 37,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check for any oil leakage from Differential assembly.",
                "sort_order": 38,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check for any damages, cracks and rust formation on under carriage components and chassis frame",
                "sort_order": 39,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check for all lv wiring harness condition and proper routing under carriage",
                "sort_order": 40,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Grease king pin and ball joint",
                "sort_order": 41,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Around the vehicle",
                "label": "Compartment Cleaning - (Rear ,LV battery, TCS & BCS) with compressed Air. (Nominal Air pressure 2 bar)",
                "sort_order": 42,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Front bellow check RHS &LHS",
                "sort_order": 43,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Rear both side bellow check RHS &LHS",
                "sort_order": 44,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Around the vehicle",
                "label": "CCS2 HV CABLE SOCKET CLEANING",
                "sort_order": 45,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Front shock absorber Mounting bolts tightening",
                "sort_order": 46,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Passenger seats mtg bolts to Stanchion poles damage or loose",
                "sort_order": 47,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Roof & floor mounting stanchion poles mounting bolts loose",
                "sort_order": 48,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "HV Battery mounting plate - 10.9 serrated bolt with 8.8 serrated nut to be used - Re-verify for loose",
                "sort_order": 49,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Grab handle broken",
                "sort_order": 50,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Front anti-roll bar both side bushes came out",
                "sort_order": 51,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Steering wheel adjustment setting issue (Comes down automatically)",
                "sort_order": 52,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Fire extinguisher bracket checks for loose and breakage mounting of unit",
                "sort_order": 53,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Rear destination Board ABS cover loose",
                "sort_order": 54,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Side destination Board ABS cover loose",
                "sort_order": 55,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Front & rear bellows inspection & piston celaning",
                "sort_order": 56,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            }
        ]
    },
    {
        "work_type_code": "10 DAYS SERVICE",
        "variant": "12M Non-AC",
        "name": "10 day inspection — 12M Non-AC",
        "items": [
            {
                "section": "Inside Bus",
                "label": "Check LV battery voltage on display",
                "sort_order": 0,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for parking brake function and symbol on display",
                "sort_order": 1,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for any fault codes on display",
                "sort_order": 2,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for steering system functionality - vibration or hardness while rotating",
                "sort_order": 3,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for led signals on display while operating combination switch and functionality of switch",
                "sort_order": 4,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for all dashboard switches working and function - interior lights, ITS,hazard light, emergency declare, doors etc.",
                "sort_order": 5,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for ITS system functionality - bdc function, speakers, announcement, destinations change, mike and all camera functions",
                "sort_order": 6,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for air condition system functionality - cooling and all blowers function (Optional)",
                "sort_order": 7,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for all USB port - function, burn marks, damages and missing",
                "sort_order": 8,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for all passenger doors operation (proper opening & closing), warning & safety function",
                "sort_order": 9,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for wiper system functionality and condition",
                "sort_order": 10,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for stanchion poles vibrations, seats and interior for any abnormalities for rusting, damage, painting etc.",
                "sort_order": 11,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for proper routing of lv wiring harness near steering column, controllers, inside dashboard",
                "sort_order": 12,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for any fuse or relay failures in interior fuse box",
                "sort_order": 13,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for main fuses (big fuses) proper mounting at LV battery compartment",
                "sort_order": 14,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check lv battery condition - voltage(bus power off), leads conditions, terminals fastening",
                "sort_order": 15,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check for all exterior lights functionality - front, parking, tail lamps & indicators",
                "sort_order": 16,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check for electric horns function",
                "sort_order": 17,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check all tyres wear, damages and deformity",
                "sort_order": 18,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check all wheel nuts and torque markings",
                "sort_order": 19,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check orvms for proper positioning and any damages",
                "sort_order": 20,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check for all flap doors locking, proper open/close, gas springs condition",
                "sort_order": 21,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check for any glass and body damages",
                "sort_order": 22,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check all LV & HV controllers for proper mounting and connectors positive locking (Rear Compartment)",
                "sort_order": 23,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check rear fuse box for proper mounting, any fuse or relay failure and any loose cables form fuse box",
                "sort_order": 24,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check all lv wiring harness for proper routing and any damages inside rear compartment",
                "sort_order": 25,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check air compressor oil levels, any leakages and abnormal noise.",
                "sort_order": 26,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check for any air leakages from air compressor lines, connectors and air dryer assembly",
                "sort_order": 27,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check steering motor and oil filter assembly for oil level, leakages and any abnormal noise",
                "sort_order": 28,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check steering motor and air compressor assembly mounting pads",
                "sort_order": 29,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check for motor coolant line assembly for coolant levels, any leakages, proper connectivity and rubber hose damages",
                "sort_order": 30,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check for coolant circulation - pumps working & clean radiator with compressed air",
                "sort_order": 31,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "HV Battery",
                "label": "Check for HV battery coolant level and coolant line condition for any leakages, rubber hose condition and routing.",
                "sort_order": 32,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "HV Battery",
                "label": "Check for HV battery coolant system working",
                "sort_order": 33,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check for HV battery mountings nuts & bolt & retighting with torque (",
                "sort_order": 34,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check all air lines and valves (EBS, brake modulators, suspension, ECAS solenoid valve etc.) for any air leakage",
                "sort_order": 35,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check all shock absorbers for any oil leakage and air springs condition and any air leakages. Retight with Shockabsorber bolts with torque",
                "sort_order": 36,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check all bushes for any damage or deformities - Anti Roll Bar, Link Rod, Traction Rods",
                "sort_order": 37,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check for any oil leakage from Differential assembly.",
                "sort_order": 38,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check for any damages, cracks and rust formation on under carriage components and chassis frame",
                "sort_order": 39,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check for all lv wiring harness condition and proper routing under carriage",
                "sort_order": 40,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Grease king pin and ball joint",
                "sort_order": 41,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Around the vehicle",
                "label": "Compartment Cleaning - (Rear ,LV battery, TCS & BCS) with compressed Air. (Nominal Air pressure 2 bar)",
                "sort_order": 42,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Front bellow check RHS &LHS",
                "sort_order": 43,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Rear both side bellow check RHS &LHS",
                "sort_order": 44,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Around the vehicle",
                "label": "CCS2 HV CABLE SOCKET CLEANING",
                "sort_order": 45,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Front shock absorber Mounting bolts tightening",
                "sort_order": 46,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Passenger seats mtg bolts to Stanchion poles damage or loose",
                "sort_order": 47,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Roof & floor mounting stanchion poles mounting bolts loose",
                "sort_order": 48,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "HV Battery mounting plate - 10.9 serrated bolt with 8.8 serrated nut to be used - Re-verify for loose",
                "sort_order": 49,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Grab handle broken",
                "sort_order": 50,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Front anti-roll bar both side bushes came out",
                "sort_order": 51,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Steering wheel adjustment setting issue (Comes down automatically)",
                "sort_order": 52,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Fire extinguisher bracket checks for loose and breakage mounting of unit",
                "sort_order": 53,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Rear destination Board ABS cover loose",
                "sort_order": 54,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Side destination Board ABS cover loose",
                "sort_order": 55,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Front & rear bellows inspection & piston celaning",
                "sort_order": 56,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            }
        ]
    },
    {
        "work_type_code": "10 DAYS SERVICE",
        "variant": "9M",
        "name": "10 day inspection — 9M",
        "items": [
            {
                "section": "Inside Bus",
                "label": "Check LV battery voltage on display and record",
                "sort_order": 0,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for parking brake function and symbol on display",
                "sort_order": 1,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for any fault codes on display and record",
                "sort_order": 2,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for steering system functionality - vibration or hardness while rotating",
                "sort_order": 3,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for led signals on display while operating combination switch and functionality of switch",
                "sort_order": 4,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for all dashboard switches working and function - interior lights, ITS,hazard light, emergency declare, doors etc.",
                "sort_order": 5,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for ITMS system functionality - bdc function, speakers, announcement, destinations change, mike and all camera functions",
                "sort_order": 6,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for air condition system functionality - cooling and all blowers function (Optional)",
                "sort_order": 7,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for all USB port - function, burn marks, damages and missing",
                "sort_order": 8,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for all passenger doors operation (proper opening & closing), warning & safety function",
                "sort_order": 9,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for wiper system functionality and condition",
                "sort_order": 10,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for stanchion poles vibrations, seats and interior for any abnormalities for rusting, damage, painting etc.",
                "sort_order": 11,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for proper routing of LV wiring harness near steering column, controllers, inside dashboard",
                "sort_order": 12,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for any fuse or relay failures in interior fuse box",
                "sort_order": 13,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Inside Bus",
                "label": "Check for main fuses (big fuses) proper mounting at LV battery compartment",
                "sort_order": 14,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check LV battery condition - voltage(bus power off), leads conditions, terminals fastening",
                "sort_order": 15,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check for all exterior lights functionality - front, parking, tail lamps & indicators",
                "sort_order": 16,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check for electric horns function",
                "sort_order": 17,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check all tyres wear, damages and deformity",
                "sort_order": 18,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check all wheel nuts and torque markings",
                "sort_order": 19,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check orvms for proper positioning and any damages",
                "sort_order": 20,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check for all flap doors locking, proper open/close, gas springs condition",
                "sort_order": 21,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Outside Bus",
                "label": "Check for any glass and body damages",
                "sort_order": 22,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check all LV & HV controllers for proper mounting and connectors positive locking (Rear Compartment)",
                "sort_order": 23,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check rear fuse box for proper mounting, any fuse or relay failure and any loose cables form fuse box",
                "sort_order": 24,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check all LV wiring harness for proper routing and any damages inside rear compartment",
                "sort_order": 25,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check air compressor oil levels, any leakages and abnormal noise.",
                "sort_order": 26,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check for any air leakages from air compressor lines, connectors and air dryer assembly",
                "sort_order": 27,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check steering motor and oil filter assembly for oil level, leakages and any abnormal noise",
                "sort_order": 28,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check steering motor and air compressor assembly mounting pads",
                "sort_order": 29,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check for motor coolant line assembly for coolant levels, any leakages, proper connectivity and rubber hose damages",
                "sort_order": 30,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "REAR SIDE",
                "label": "Check for coolant circulation - pumps working & clean radiator with compressed air",
                "sort_order": 31,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "HV Battery",
                "label": "Check for HV battery coolant level and coolant line condition for any leakages, rubber hose condition and routing.",
                "sort_order": 32,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "HV Battery",
                "label": "Check for HV battery coolant system working",
                "sort_order": 33,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check for HV battery mountings nuts & bolt & tightening with torque",
                "sort_order": 34,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check all air lines and valves (EBS, brake modulators, suspension, ECAS solenoid valves etc.) for any air leakage",
                "sort_order": 35,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check all shock absorbs for any oil leakage and air springs condition and any air leakages. Re-tight with Shockabsorber bolts with torque",
                "sort_order": 36,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check all bushes for any damage or deformities - Anti Roll Bar, Link Rod, Traction Rods",
                "sort_order": 37,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check for any oil leakage from Differential assembly.",
                "sort_order": 38,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check for any damages, cracks and rust formation on under carriage components and chassis frame",
                "sort_order": 39,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Check for all LV wiring harness condition and proper routing under carriage",
                "sort_order": 40,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Grease king pin and ball joint",
                "sort_order": 41,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Around the vehicle",
                "label": "Compartment Cleaning - (Rear ,LV battery, TCS & BCS) with compressed Air. (Nominal Air pressure 2 bar)",
                "sort_order": 42,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Front bellow check RHS & LHS",
                "sort_order": 43,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Under Carriage",
                "label": "Rear both side bellow check RHS & LHS",
                "sort_order": 44,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Around the vehicle",
                "label": "CCS2 HV CABLE SOCKET CLEANING",
                "sort_order": 45,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Front shock absorb-er Mounting bolts tightening(M10-T-50- 55Nm)",
                "sort_order": 46,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Passenger seats mtg bolts to Stanchion poles damage or loose",
                "sort_order": 47,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Roof & floor mounting stanchion poles mounting bolts loose",
                "sort_order": 48,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "HV Battery mounting plate - 10.9 serrated bolt(T-170+-15) with 8.8 serrated nut to be used - Re-verify for loose",
                "sort_order": 49,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Grab handle check.",
                "sort_order": 50,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Front anti-roll bar both side bushes check.",
                "sort_order": 51,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Steering wheel adjustment setting issue (Comes down automatically)",
                "sort_order": 52,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Fire extinguisher bracket checks for loose and breakage mounting of unit",
                "sort_order": 53,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Rear destination Board ABS cover loose",
                "sort_order": 54,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Side destination Board ABS cover loose",
                "sort_order": 55,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "Re-verify",
                "label": "Front and rear bellows inspection and piston cleaning.",
                "sort_order": 56,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            }
        ]
    },
    {
        "work_type_code": "D.I",
        "variant": "12M AC",
        "name": "Daily inspection — 12M AC",
        "items": [
            {
                "section": "",
                "label": "Check Power Steering oil level.",
                "sort_order": 0,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Water level in windscreen washer .",
                "sort_order": 1,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Wiper Blades/ Operations.",
                "sort_order": 2,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "BCS & TCS coolant level.",
                "sort_order": 3,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Parking brake Check.",
                "sort_order": 4,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Air pressure upto 9.5 bar",
                "sort_order": 5,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Both pax doors.",
                "sort_order": 6,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "All Destination boards.",
                "sort_order": 7,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Fault codes on 7' Display",
                "sort_order": 8,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Check horn.& All lights",
                "sort_order": 9,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "External and Internal Body damages.",
                "sort_order": 10,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Check Fire extinguisher 1,2,",
                "sort_order": 11,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Check Ac Blower",
                "sort_order": 12,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Check AC Cooling",
                "sort_order": 13,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            }
        ]
    },
    {
        "work_type_code": "D.I",
        "variant": "12M Non-AC",
        "name": "Daily inspection — 12M Non-AC",
        "items": [
            {
                "section": "",
                "label": "Check Power Steering oil level.",
                "sort_order": 0,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Water level in windscreen washer .",
                "sort_order": 1,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Wiper Blades/ Operations.",
                "sort_order": 2,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "BCS & TCS coolant level.",
                "sort_order": 3,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Parking brake Check.",
                "sort_order": 4,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Air pressure upto 9.5 bar",
                "sort_order": 5,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Both pax doors.",
                "sort_order": 6,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "All Destination boards.",
                "sort_order": 7,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Fault codes on 7' Display",
                "sort_order": 8,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Check horn.& All lights",
                "sort_order": 9,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "External and Internal Body damages.",
                "sort_order": 10,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Check Fire extinguisher 1,2,",
                "sort_order": 11,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            }
        ]
    },
    {
        "work_type_code": "D.I",
        "variant": "9M",
        "name": "Daily inspection — 9M",
        "items": [
            {
                "section": "",
                "label": "Steering oil level. check",
                "sort_order": 0,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Wiper Blades check",
                "sort_order": 1,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Wind screen water check",
                "sort_order": 2,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Check BCS & TCS coolant level.check",
                "sort_order": 3,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Parking brake function check",
                "sort_order": 4,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Air pressure building upto 9.5 Bar check",
                "sort_order": 5,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Both Pax door check",
                "sort_order": 6,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "All lights check",
                "sort_order": 7,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Destination Board check",
                "sort_order": 8,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Driver fan check",
                "sort_order": 9,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "7\" diplay fault",
                "sort_order": 10,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Fire Extinguisher check 1st 2nd 3rd",
                "sort_order": 11,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "Horn check",
                "sort_order": 12,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            },
            {
                "section": "",
                "label": "External body Damge check",
                "sort_order": 13,
                "response_type": "ok_not_ok",
                "is_required": True,
                "chart_key": None
            }
        ]
    }
]
