"""The P.M docking checklist, 12M AC / 12M Non-AC variants — migration 0016.

Same approach as `checklists_v2.py` (9M): read by hand from
`data/MBMT/August/12M DOCKING SHET/1.20LAKH-12M MAINTANANCES SCHEDULE.pdf`
(not in the repository), which is the superset of every lower milestone.

Unlike the 9M folder, this one PDF is shared by two vehicle-master
`checklist_variant` values — "12M AC" and "12M Non-AC" — with sections
explicitly marked "(Applicable to AC Bus)" / "(Applicable to Non AC Bus)".
72 items are common to both; AC adds its own 7-item AC + BCS block, Non-AC
adds its own 2-item Battery Cooling System block instead — mirroring how the
D.I and ten-day checklists already split these two variants. A bus's own
`checklist_variant` on its vehicle-master record is what picks between them,
same mechanism as every other checklist in this file.

Two values in the source read as likely typos, transcribed as printed rather
than silently corrected: the AC bus's Evaporator Coil interval ("700000 KM or
7 year") and compressor mounting interval ("900000KM or 9 years") — the 9M
sheet's equivalent lines read 40,000 km/1 year and 70,000 km/2 years. Worth
confirming with the depot before relying on either as a real service trigger.

Do not edit this file once a migration reading it has run — see
`checklists_v1.py`'s note.
"""
from __future__ import annotations

from typing import Any

#: Common to both AC and Non-AC 12M buses — sort_order 0-71.
_COMMON: list[dict[str, Any]] = [
    # --- Inception ---------------------------------------------------
    {"section": "Inception", "label": "Road Test — inspect at every service", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Inception", "label": "Check for abnormal noise — inspect at every service", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Inception", "label": "Check for instrument cluster functionality — inspect at every service", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Inception", "label": "Check vehicle speed — inspect at every service", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Inception", "label": "Connect diagnostic tool and check for any DTC — inspect at every service", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Inception", "label": "Correct and clear the DTC — inspect at every service", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    # --- Clean & Wash -------------------------------------------------
    {"section": "Clean & Wash", "label": "Clean & wash vehicle — it's electric, no washing on/around seats, dashboard & HV components — every service", "response_type": "ok_not_ok", "is_required": True, "chart_key": "washing"},
    # --- HV Battery -----------------------------------------------------
    {"section": "HV Battery", "label": "Battery support — tighten support/mounting bolts, inspect at every service (110±8 Nm)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "HV Battery", "label": "Check whether the controller high voltage connector is connected firmly — inspect at every service", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "HV Battery", "label": "Battery health checks — at every 20,000 km", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "HV Battery", "label": "HV cables — check for abrasion, wear or cut marks (follow HV safety guidelines) — inspect at every 40,000 km", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "HV Battery", "label": "HV cables — check tightening torque of HV access outer lid covers (inverter, traction motor, DC junction boxes) & all glands — inspect at every 40,000 km", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    # --- Traction Motor & Motor Controller ------------------------------
    {"section": "Traction Motor & Motor Controller", "label": "Traction motor support/mounting bolts — tighten & replace rubber mountings if cracked (20 Nm)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Traction Motor & Motor Controller", "label": "Traction motor controller mounting bolts — check tightening torque of inverter mounting bolts, earthing point, power/signal connectors (17~20 Nm)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Traction Motor & Motor Controller", "label": "Traction motor controller — check for proper connection of HV cables; if loose, shut down system and tighten with calibrated torque wrench", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    # --- Auxiliary Controller & DC-DC -----------------------------------
    {"section": "Auxiliary Controller & DC-DC", "label": "Support/mounting bolts — tighten, inspect at every service (30±2 Nm)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Auxiliary Controller & DC-DC", "label": "Wiring & terminals — look for damaged, unsecured or loose wires and terminals (12~14 Nm)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    # --- Traction Cooling System -----------------------------------------
    {"section": "Traction Cooling System", "label": "Support/mounting bolts — tighten, inspect at every service (12-15 Nm)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Traction Cooling System", "label": "Radiator — check for clogging, clean with compressed air if necessary (max 5 bar)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Traction Cooling System", "label": "Fan drive — visual inspection of W/H connections & LV connections to coolant pump", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Traction Cooling System", "label": "Coolant hose — check hoses and joints for leakages/damages, replace if damaged", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Traction Cooling System", "label": "Coolant — check traction coolant level, correct if required; drain & replace (50-50 ethylene glycol + distilled water) at 1 lakh km or 1.5 years, whichever earlier", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    # --- High Voltage Power Distribution Unit (HVPDU) ----------------------
    {"section": "High Voltage Power Distribution Unit (HVPDU)", "label": "Support/mounting bolts — tighten, inspect at every service (46±4 Nm)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "High Voltage Power Distribution Unit (HVPDU)", "label": "HV cables — check functionality of HV contact terminal with multimeter; check for blackening/chattering/discoloration, replace if necessary", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    # --- Steering and Front Axle -------------------------------------------
    {"section": "Steering and Front Axle", "label": "King pin — lubricate every 10,000 km", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Steering and Front Axle", "label": "Steering linkages — lubricate drag link, steering column and tie rod greasing points every 10,000 km", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Steering and Front Axle", "label": "Power steering oil & filter — inspect for leakage across gear box, pipes & cylinders, correct & top up; replace oil & filter at 80,000 km", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Steering and Front Axle", "label": "Steering gear box / steering pump / idler arm / tie rod / drag link / pitman arm mounting fasteners — inspect for looseness and tighten if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Steering and Front Axle", "label": "Steering wheel — inspect free play & adjust if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Steering and Front Axle", "label": "Ball joints (tie-rod, drag-link) — inspect free play and replace if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Steering and Front Axle", "label": "Steering system — inspect for proper functioning (hardness, wobbling, noise)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    # --- Propeller Shaft and Rear Axle --------------------------------------
    {"section": "Propeller Shaft and Rear Axle", "label": "Propeller shaft flange bolts — tighten (110±8 Nm)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Propeller Shaft and Rear Axle", "label": "Differential oil (rear) — inspect for leakage, correct & top up if required; replace oil at specified interval", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    # --- Air Suspension --------------------------------------------------------
    {"section": "Air Suspension", "label": "Fasteners — tighten (rear ARB & shock absorber 170±15 Nm; front ARB & below 110±8 Nm)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Air Suspension", "label": "Bellows — inspect for cracks, damage, leakage, replace if required; clean from dust/foreign particles", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Air Suspension", "label": "Parallel link bushes/radius rod — inspect for wear/play and replace if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Air Suspension", "label": "Leveling valve & bellows — inspect height and correct; ensure no oil deposition/foreign or metal particles trapped", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Air Suspension", "label": "Pneumatic lines/connectors — inspect for leakage and correct; replace if damaged", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Air Suspension", "label": "Anti-roll bar bush — check and replace if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    # --- Brake System ------------------------------------------------------------
    {"section": "Brake System", "label": "Caliper, excluder guide sleeve, piston, adjuster cap & seal actuator — inspect for any damage; check and replace kit boot if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Brake System", "label": "Brake disc — inspect for disc wear every service (disc thickness limit 37 mm); replace if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Brake System", "label": "Brake drum/lined shoe — inspect at every 20,000 km; inspect lining condition and lining-to-drum clearance; inspect drum for cracks/score marks/damage and drum service limit", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Brake System", "label": "Brake pad — inspect at every service; replace if wear indicator alarms", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Brake System", "label": "Air disc brake mounting torque — inspect", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    # --- Air Compressor -----------------------------------------------------------
    {"section": "Air Compressor", "label": "Air compressor oil — inspect oil level/condition & top up if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Air Compressor", "label": "Compressor air filter along with clamps/joints/pipes — on red indication replace primary filter every time, safety element every 3rd primary change", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Air Compressor", "label": "Cooling fan, damper, inlet hose (resonator & cyl. head) — replace every two years or 2,00,000 km, whichever earlier", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Air Compressor", "label": "Electronic choke indicator, temp high alert from motor, earthing, 3/2 solenoid valve functioning, pipe routing — inspect every 10,000 km", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    # --- DDU/APU --------------------------------------------------------------------
    {"section": "DDU/APU", "label": "APU hoses — check for cut-in & cut-out and leakage in the system", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "DDU/APU", "label": "APU functioning — check for moisture/water collection in the reservoir", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    # --- Wheel Ends --------------------------------------------------------------------
    {"section": "Wheel Ends", "label": "Wheels (tyre) — inspect tyre pressure and correct if required; inspect condition/wear (TWI) and correct if required (also check weekly)", "response_type": "ok_not_ok", "is_required": True, "chart_key": "tyre_pressure"},
    {"section": "Wheel Ends", "label": "Front & rear tyre rotation — every 10,000 km", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Wheel Ends", "label": "Front & rear wheel alignment & tyre rotation — every 20,000 km (1st at 3,000 km)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Wheel Ends", "label": "Wheel hub bearing front & rear — every 30,000 km clean and lubricate with fresh grease & adjust hub bearing play", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Wheel Ends", "label": "Wheel nuts — wheel nut tightening (520±40 Nm)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    # --- Electrical --------------------------------------------------------------------
    {"section": "Electrical", "label": "Check error codes — check for VCU errors with diagnostic tool; check status and clear error codes", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Electrical", "label": "General checking (physical condition) — inspect wiring harnesses for looseness, pinching, cuts, proper connection; check interface connector, loose connections, fuse, relay and sensors; accessories connections from add-on connector only", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Electrical", "label": "LV battery (24V) — inspect cleanliness of terminals & apply petroleum jelly; check cables not loose; inspect correct voltage & charging current, correct if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Electrical", "label": "Switch, horn, lamp & instrument function — inspect for proper operation and replace if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Electrical", "label": "Ground terminals (physical condition) — check tightening torques and health of LV and HV ground terminals", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    # --- Bus Body --------------------------------------------------------------------
    {"section": "Bus Body", "label": "Body mounting & outrigger bracket bolts — inspect & tighten if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Bus Body", "label": "Door hinge (driver door & JK door) & locks & latches; rear compartment flap hinge, locks & latches — lubricate and inspect for proper functioning; inspect gas stay condition of rear compartment flap", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Bus Body", "label": "Seat belt and mountings — inspect for cracks, damages and tightness of mounting bolts, correct if required (520±40 Nm)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Bus Body", "label": "Driver, co-driver seat & passenger seat — inspect & tighten mounting bolts if required (21-26 Nm)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Bus Body", "label": "ORVM & IRVM — inspect & tighten mounting bolts if required (51±5 Nm)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Bus Body", "label": "Body sheet (panel) condition — inspect for pasting & correct if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Bus Body", "label": "Sliding glass (driver door/window) — inspect for smooth movement/lock functioning/lock channel condition, correct if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Bus Body", "label": "Lights (interior and exterior) — inspect for proper functioning and replace if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Bus Body", "label": "Passenger door smooth operation — inspect and correct if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Bus Body", "label": "Flap door smooth operation (obstruction-free opening/closing, locks functioning, gas-stay condition) — inspect and correct if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Bus Body", "label": "Visual under-body inspection for superstructure welding joints / ply board condition — inspect and correct if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Bus Body", "label": "Bus interior components, hatrack, stanchions etc — inspect & tighten mounting bolts if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
]

#: AC bus only — "AC + BCS (Applicable to AC Bus)".
_AC_ONLY: list[dict[str, Any]] = [
    {"section": "AC + BCS (AC bus)", "label": "Check control panel for its normal operation (compressed air max 2 bar)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "AC + BCS (AC bus)", "label": "Recirculated air filter (return air filter) — clean every service, replace every 30,000 km or 1 year, whichever earlier", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "AC + BCS (AC bus)", "label": "Evaporator air filter — clean every service, replace every 70,000 km or 2 years, whichever earlier", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "AC + BCS (AC bus)", "label": "Condenser coil — clean at every service (compressed air max 2 bar)", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    # As printed — likely a typo (compare 9M's equivalent line: 40,000 km / 1 year). See module docstring; confirm with the depot.
    {"section": "AC + BCS (AC bus)", "label": "Evaporator coil — clean every 7,00,000 km or 7 years, whichever earlier, or if required", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    # As printed — likely a typo (compare 9M's equivalent line: 70,000 km / 2 years). See module docstring; confirm with the depot.
    {"section": "AC + BCS (AC bus)", "label": "Mounting of compressor — replace every 9,00,000 km or 9 years, whichever earlier", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "AC + BCS (AC bus)", "label": "Hoses (chiller, radiator, motor coolant) — inspect for cracks/damage, replace if required; inspect and tighten mounting clamps", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
]

#: Non-AC bus only — "Battery Cooling System (Applicable to Non AC Bus)".
_NON_AC_ONLY: list[dict[str, Any]] = [
    {"section": "Battery Cooling System (Non-AC bus)", "label": "Coolant — inspect for leakage, correct & top up if required; check level on sight glass; replace at specified interval", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
    {"section": "Battery Cooling System (Non-AC bus)", "label": "Hoses (chiller, radiator, motor coolant) — inspect for cracks/damage, replace if required; inspect and tighten mounting clamps", "response_type": "ok_not_ok", "is_required": True, "chart_key": None},
]


def _numbered(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [{**item, "sort_order": i} for i, item in enumerate(items)]


CHECKLISTS: list[dict[str, Any]] = [
    {
        "work_type_code": "P.M",
        "variant": "12M AC",
        "name": "Preventive maintenance docking — 12M AC",
        "items": _numbered(_COMMON + _AC_ONLY),
    },
    {
        "work_type_code": "P.M",
        "variant": "12M Non-AC",
        "name": "Preventive maintenance docking — 12M Non-AC",
        "items": _numbered(_COMMON + _NON_AC_ONLY),
    },
]
